### ISSUE TITLE
defense on the client prevents tablist scoreboard objectives from rendering propperly

### ISSUE THREAD

**Issue by o800** [Mortimer-Kerman/Defense#5]
without defence
![Screenshot 2024-10-02 152641a](https://github.com/user-attachments/assets/a8aa8d4c-ee00-4f4a-b634-4b92885d885c)
![Screenshot 2024-10-02 152346a](https://github.com/user-attachments/assets/8f2a3909-8213-460e-aab5-76733a22b49b)

with defence
![Screenshot 2024-10-02 153911a](https://github.com/user-attachments/assets/613eecc3-6b23-4ae7-b164-36868c8851e8)
![Screenshot 2024-10-02 153831a](https://github.com/user-attachments/assets/d3a576b4-f870-4fed-9f48-53dc5de8b49d)

**Comment by Mortimer-Kerman** [comment]
> without defence
> ![Screenshot 2024-10-02 152641a](https://github.com/user-attachments/assets/a8aa8d4c-ee00-4f4a-b634-4b92885d885c)
> ![Screenshot 2024-10-02 152346a](https://github.com/user-attachments/assets/8f2a3909-8213-460e-aab5-76733a22b49b)
> 
> with defence
> ![Screenshot 2024-10-02 153911a](https://github.com/user-attachments/assets/613eecc3-6b23-4ae7-b164-36868c8851e8)
> ![Screenshot 2024-10-02 153831a](https://github.com/user-attachments/assets/d3a576b4-f870-4fed-9f48-53dc5de8b49d)
> 

Could you give me more details, tell me which commands you have run and could you please try to send bigger screenshots without hiding stuff with paint please? I can't see what's going on

And if you're not comfortable posting these screenshots here, you can dm them to me on Discord

**Comment by o800** [comment]
to reproduce, create any scoreboard objective, then set it to display in the tablist with /scoreboard objectives setdisplay list [objective name]. i have reproduced the bug on a fabric install with only defense and fabric-api installed.

**Comment by Mortimer-Kerman** [comment]
Bug confirmed, working on it
![image](https://github.com/user-attachments/assets/eb90e63a-4813-4238-8c39-822f30ad4ec5)

**Comment by Mortimer-Kerman** [comment]
okay just to warn, an actual fix was published on modrinth
